import "./fonts/font-imports.css";
import "./globals.css";

import SmoothScroll from "./components/SmoothScroll";
// Define the font stack with Arial and sans-serif as fallbacks

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
