import "./fonts/font-imports.css";
import "./globals.css";

import CustomCursor from "./components/CustomCursor";

// Define the font stack with Arial and sans-serif as fallbacks


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html scroll-behavior="smooth" lang="en" >
      <body scroll-behavior="smooth" className={` h-[2000px]`}>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
